name: in_app_notification_example
description: 'Example of in_app_notification usage'
publish_to:  none

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  in_app_notifications:
    path: ../
  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - ./assets/img/
