name: flutter_notification_queue_example
description: 'Example of flutter_notification_queue usage'
publish_to:  none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter_notification_queue:
    path: ../
  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - ./assets/img/
