name: in_app_notification_example
description: 'Example of in_app_notification usage'
publish_to:  none

environment:
  sdk: '>=2.18.0 <=3.9.0'
  flutter: ">=3.0.0"

dependencies:
  in_app_notifications:
    path: ../
  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  image: assets/img/logo.png
  color: "#FCFCFB"
  android: true
  web: true


flutter:
  uses-material-design: true

  assets:
    - ./assets/img/
